export const books = [
  {
    id: 1,
    Title: "To Kill a Mockingbird",
    Author: "Harper Lee",
    PublicationDate: 1960,
    Pages: 281,
    CoverImage: "https://m.media-amazon.com/images/I/81gepf1eMqL._SL1500_.jpg",
    Description: "A classic novel set in the 1930s Deep South, tackling issues of race and justice through the eyes of young Scout Finch.",
    Category: "Fiction",
    Rating: 4.8
  },
  {
    id: 2,
    Title: "1984",
    Author: "George Orwell",
    PublicationDate: 1949,
    Pages: 328,
    CoverImage: "https://m.media-amazon.com/images/I/51BIA4rraeL._AC_UF1000,1000_QL80_.jpg",
    Description: "A dystopian novel about a totalitarian regime that uses surveillance and propaganda to control its citizens.",
    Category: "Dystopian",
    Rating: 4.7
  },
  {
    id: 3,
    Title: "The Great Gatsby",
    Author: "F. Scott Fitzgerald",
    PublicationDate: 1925,
    Pages: 180,
    CoverImage: "https://m.media-amazon.com/images/I/81Q6WkLhX4L._UF1000,1000_QL80_.jpg",
    Description: "A tale of love, wealth, and social change in 1920s America.",
    Category: "Classics",
    Rating: 4.6
  },
  {
    id: 4,
    Title: "Moby-Dick",
    Author: "Herman Melville",
    PublicationDate: 1851,
    Pages: 635,
    CoverImage: "https://m.media-amazon.com/images/I/81YOuOGFCJL._AC_UL200_.jpg",
    Description: "A sailor's journey aboard the Pequod, pursuing the elusive white whale, Moby Dick.",
    Category: "Adventure",
    Rating: 4.2
  },
  {
    id: 5,
    Title: "The Catcher in the Rye",
    Author: "J.D. Salinger",
    PublicationDate: 1951,
    Pages: 277,
    CoverImage: "https://m.media-amazon.com/images/I/81OthjkJBuL._AC_UL200_.jpg",
    Description: "The story of Holden Caulfield, a teenager struggling with alienation in post-WWII New York.",
    Category: "Fiction",
    Rating: 4.3
  },
  {
    id: 6,
    Title: "Pride and Prejudice",
    Author: "Jane Austen",
    PublicationDate: 1813,
    Pages: 279,
    CoverImage: "https://m.media-amazon.com/images/I/412bjj40hoL._SY445_SX342_.jpg",
    Description: "A romantic novel about Elizabeth Bennet and her evolving relationship with the wealthy, aloof Mr. Darcy.",
    Category: "Romance",
    Rating: 4.9
  },
  {
    id: 7,
    Title: "The Hobbit",
    Author: "J.R.R. Tolkien",
    PublicationDate: 1937,
    Pages: 310,
    CoverImage: "https://m.media-amazon.com/images/I/51QnRBHJ+sL._SY445_SX342_.jpg",
    Description: "The prequel to the Lord of the Rings, following Bilbo Baggins' adventure to reclaim a stolen treasure.",
    Category: "Fantasy",
    Rating: 4.8
  },
  {
    id: 8,
    Title: "Fahrenheit 451",
    Author: "Ray Bradbury",
    PublicationDate: 1953,
    Pages: 158,
    CoverImage: "https://m.media-amazon.com/images/I/61l8LHt4MeL._AC_UF1000,1000_QL80_.jpg",
    Description: "In a dystopian society, firemen burn books to maintain control, and one firefighter questions his role in society.",
    Category: "Science Fiction",
    Rating: 4.4
  },
  {
    id: 9,
    Title: "Brave New World",
    Author: "Aldous Huxley",
    PublicationDate: 1932,
    Pages: 268,
    CoverImage: "https://m.media-amazon.com/images/I/917t3Joq2WL.jpg",
    Description: "A dystopian world where humans are controlled and conditioned to fit into a rigid social hierarchy.",
    Category: "Dystopian",
    Rating: 4.5
  },
  {
    id: 10,
    Title: "The Lord of the Rings",
    Author: "J.R.R. Tolkien",
    PublicationDate: 1954,
    Pages: 1178,
    CoverImage: "https://m.media-amazon.com/images/I/415JmdZgIHL._SY445_SX342_.jpg",
    Description: "The epic fantasy tale of Frodo Baggins and his quest to destroy the One Ring.",
    Category: "Fantasy",
    Rating: 4.9
  },
  {
    id: 11,
    Title: "The Chronicles of Narnia",
    Author: "C.S. Lewis",
    PublicationDate: 1950,
    Pages: 767,
    CoverImage: "https://m.media-amazon.com/images/I/51Uq3ORSmQL._SY445_SX342_.jpg",
    Description: "A series of seven fantasy novels set in the magical world of Narnia.",
    Category: "Fantasy",
    Rating: 4.8
  },
  {
    id: 12,
    Title: "The Catcher in the Rye",
    Author: "J.D. Salinger",
    PublicationDate: 1951,
    Pages: 277,
    CoverImage: "https://m.media-amazon.com/images/I/81OthjkJBuL._AC_UL200_.jpg",
    Description: "The story of Holden Caulfield, a teenager struggling with alienation in post-WWII New York.",
    Category: "Fiction",
    Rating: 4.3
  },
  {
    id: 13,
    Title: "The Road",
    Author: "Cormac McCarthy",
    PublicationDate: 2006,
    Pages: 287,
    CoverImage: "https://m.media-amazon.com/images/I/81ChFcmhXDL._AC_UF1000,1000_QL80_.jpg",
    Description: "A father and son struggle to survive in a post-apocalyptic world, facing harsh conditions.",
    Category: "Post-Apocalyptic",
    Rating: 4.6
  },
  {
    id: 14,
    Title: "Harry Potter and the Sorcerer's Stone",
    Author: "J.K. Rowling",
    PublicationDate: 1997,
    Pages: 309,
    CoverImage: "https://m.media-amazon.com/images/I/51zZ3SAulVL._SY445_SX342_.jpg",
    Description: "The first book in the Harry Potter series, where a young boy discovers he is a wizard.",
    Category: "Fantasy",
    Rating: 4.9
  },
  {
    id: 15,
    Title: "Wuthering Heights",
    Author: "Emily Brontë",
    PublicationDate: 1847,
    Pages: 400,
    CoverImage: "https://m.media-amazon.com/images/I/81-jFO1dm8L._UF1000,1000_QL80_.jpg",
    Description: "A passionate and tragic love story set on the moors of England between Heathcliff and Catherine Earnshaw.",
    Category: "Romance",
    Rating: 4.6
  },
  {
    id: 16,
    Title: "Jane Eyre",
    Author: "Charlotte Brontë",
    PublicationDate: 1847,
    Pages: 500,
    CoverImage: "https://m.media-amazon.com/images/I/411Jk7G2W3L._SX342_SY445_.jpg",
    Description: "The story of an orphan who becomes a governess and falls in love with her enigmatic employer, Mr. Rochester.",
    Category: "Classics",
    Rating: 4.8
  },
  {
    id: 17,
    Title: "The Picture of Dorian Gray",
    Author: "Oscar Wilde",
    PublicationDate: 1890,
    Pages: 254,
    CoverImage: "https://m.media-amazon.com/images/I/71fm0Ap7JcL._AC_UF1000,1000_QL80_.jpg",
    Description: "A young man remains youthful while his portrait ages, revealing his true character.",
    Category: "Philosophy",
    Rating: 4.4
  },
  {
    id: 18,
    Title: "The Outsiders",
    Author: "S.E. Hinton",
    PublicationDate: 1967,
    Pages: 180,
    CoverImage: "https://m.media-amazon.com/images/I/81nxH2IrP-L._AC_UF1000,1000_QL80_.jpg",
    Description: "A coming-of-age novel about the conflict between two rival groups of teenagers in a small American town.",
    Category: "Young Adult",
    Rating: 4.6
  },
  {
    id: 19,
    Title: "The Secret Garden",
    Author: "Frances Hodgson Burnett",
    PublicationDate: 1911,
    Pages: 331,
    CoverImage: "https://m.media-amazon.com/images/I/71ppraw-V4L.jpg",
    Description: "A young girl discovers a hidden garden and transforms her life as well as those of the people around her.",
    Category: "Children's Literature",
    Rating: 4.7
  },
  {
    id: 20,
    Title: "The Bell Jar",
    Author: "Sylvia Plath",
    PublicationDate: 1963,
    Pages: 288,
    CoverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQroGA1VLeFuxx_s7F_s6cdQshC6FSg7xU1tA&s",
    Description: "A semi-autobiographical novel that follows a young woman’s descent into mental illness.",
    Category: "Literature",
    Rating: 4.3
  },
  {
    id: 21,
    Title: "The Shining",
    Author: "Stephen King",
    PublicationDate: 1977,
    Pages: 447,
    CoverImage: "https://m.media-amazon.com/images/I/91U7HNa2NQL.jpg",
    Description: "A family stays in an isolated hotel where strange, terrifying events unfold.",
    Category: "Horror",
    Rating: 4.7
  },
  {
    id: 22,
    Title: "The Hitchhiker's Guide to the Galaxy",
    Author: "Douglas Adams",
    PublicationDate: 1979,
    Pages: 224,
    CoverImage: "https://m.media-amazon.com/images/I/81AAMH2S0LL._AC_UF1000,1000_QL80_.jpg",
    Description: "A comedic science fiction series that follows Arthur Dent as he travels through space.",
    Category: "Sci-Fi",
    Rating: 4.6
  },
  {
    id: 23,
    Title: "The Martian",
    Author: "Andy Weir",
    PublicationDate: 2011,
    Pages: 369,
    CoverImage: "https://m.media-amazon.com/images/I/51QimqeXMXL._SL1200_.jpg",
    Description: "An astronaut is stranded on Mars and must use his skills to survive.",
    Category: "Sci-Fi",
    Rating: 4.8
  },
  {
    id: 24,
    Title: "The Girl on the Train",
    Author: "Paula Hawkins",
    PublicationDate: 2015,
    Pages: 395,
    CoverImage: "https://m.media-amazon.com/images/I/81-Q2OAVeXL._AC_UF1000,1000_QL80_.jpg",
    Description: "A psychological thriller about a woman who becomes involved in a mysterious disappearance.",
    Category: "Thriller",
    Rating: 4.2
  },
  {
    id: 25,
    Title: "The Godfather",
    Author: "Mario Puzo",
    PublicationDate: 1969,
    Pages: 448,
    CoverImage: "https://m.media-amazon.com/images/I/61zAyF3qLnL._AC_UF1000,1000_QL80_.jpg",
    Description: "The saga of the powerful Corleone crime family, and their rise and fall in America.",
    Category: "Crime",
    Rating: 4.7
  },
  {
    id: 26,
    Title: "Gone with the Wind",
    Author: "Margaret Mitchell",
    PublicationDate: 1936,
    Pages: 1037,
    CoverImage: "https://m.media-amazon.com/images/I/61HYHjeCh+L._UF1000,1000_QL80_.jpg",
    Description: "A Southern love story set during the American Civil War and Reconstruction era.",
    Category: "Historical Fiction",
    Rating: 4.5
  },
  {
    id: 27,
    Title: "Catch-22",
    Author: "Joseph Heller",
    PublicationDate: 1961,
    Pages: 453,
    CoverImage: "https://m.media-amazon.com/images/I/71Ym0vDDWsL._AC_UF1000,1000_QL80_.jpg",
    Description: "A satirical novel about the absurdities of war and military bureaucracy.",
    Category: "Satire",
    Rating: 4.6
  },
  {
    id: 28,
    Title: "Animal Farm",
    Author: "George Orwell",
    PublicationDate: 1945,
    Pages: 112,
    CoverImage: "https://m.media-amazon.com/images/I/71JUJ6pGoIL.jpg",
    Description: "A political satire about a group of farm animals who overthrow their human owner.",
    Category: "Political Satire",
    Rating: 4.7
  },
  {
    id: 29,
    Title: "Dracula",
    Author: "Bram Stoker",
    PublicationDate: 1897,
    Pages: 488,
    CoverImage: "https://m.media-amazon.com/images/I/811hr0FIS8L._AC_UF350,350_QL80_.jpg",
    Description: "A Gothic horror novel about the infamous vampire, Count Dracula.",
    Category: "Horror",
    Rating: 4.3
  },
  {
    id: 30,
    Title: "Les Misérables",
    Author: "Victor Hugo",
    PublicationDate: 1862,
    Pages: 1232,
    CoverImage: "https://m.media-amazon.com/images/I/71-TgJbnftL._SY466_.jpg",
    Description: "A story of redemption, love, and sacrifice set against the backdrop of post-revolutionary France.",
    Category: "Historical Fiction",
    Rating: 4.8
  },
  {
    id: 31,
    Title: "The Fountainhead",
    Author: "Ayn Rand",
    PublicationDate: 1943,
    Pages: 736,
    CoverImage: "https://m.media-amazon.com/images/I/81Ifqv8AHfL.jpg",
    Description: "The story of an individualistic architect, Howard Roark, who challenges conventional ideas of art and architecture.",
    Category: "Philosophy",
    Rating: 4.5
  },
  {
    id: 32,
    Title: "A Tale of Two Cities",
    Author: "Charles Dickens",
    PublicationDate: 1859,
    Pages: 544,
    CoverImage: "https://m.media-amazon.com/images/I/71CQFGiPA+L._AC_UF1000,1000_QL80_.jpg",
    Description: "Set during the French Revolution, it contrasts the experiences of two men in Paris and London.",
    Category: "Historical Fiction",
    Rating: 4.7
  },
  {
    id: 33,
    Title: "The Alchemist",
    Author: "Paulo Coelho",
    PublicationDate: 1988,
    Pages: 208,
    CoverImage: "https://m.media-amazon.com/images/I/61HAE8zahLL._AC_UF1000,1000_QL80_.jpg",
    Description: "A young shepherd embarks on a journey to find a hidden treasure and discovers the meaning of life.",
    Category: "Adventure",
    Rating: 4.6
  },
  {
    id: 34,
    Title: "The Handmaid's Tale",
    Author: "Margaret Atwood",
    PublicationDate: 1985,
    Pages: 311,
    CoverImage: "https://m.media-amazon.com/images/I/61su39k8NUL.jpg",
    Description: "A dystopian story set in a future where women have lost their rights and are controlled by a totalitarian regime.",
    Category: "Dystopian",
    Rating: 4.5
  },
  {
    id: 35,
    Title: "The Hunger Games",
    Author: "Suzanne Collins",
    PublicationDate: 2008,
    Pages: 374,
    CoverImage: "https://m.media-amazon.com/images/I/61I24wOsn8L._AC_UF1000,1000_QL80_.jpg",
    Description: "A teenager is forced to fight in a televised, life-or-death game in a dystopian society.",
    Category: "Dystopian",
    Rating: 4.6
  },
  {
    id: 36,
    Title: "The Girl with the Dragon Tattoo",
    Author: "Stieg Larsson",
    PublicationDate: 2005,
    Pages: 465,
    CoverImage: "https://m.media-amazon.com/images/I/81YW99XIpJL._UF1000,1000_QL80_.jpg",
    Description: "A journalist and a hacker team up to solve the mystery of a missing woman from a powerful family.",
    Category: "Thriller",
    Rating: 4.4
  },
  {
    id: 37,
    Title: "The Book Thief",
    Author: "Markus Zusak",
    PublicationDate: 2005,
    Pages: 552,
    CoverImage: "https://m.media-amazon.com/images/I/81DEjYAbteL._SY466_.jpg",
    Description: "Set in Nazi Germany, a young girl finds solace in stealing books and sharing them with others.",
    Category: "Historical Fiction",
    Rating: 4.8
  },
  {
    id: 38,
    Title: "The Invisible Man",
    Author: "H.G. Wells",
    PublicationDate: 1897,
    Pages: 212,
    CoverImage: "https://m.media-amazon.com/images/I/81aUECLG01L._AC_UF1000,1000_QL80_.jpg",
    Description: "A scientist discovers the secret of invisibility, but it leads him down a path of madness.",
    Category: "Sci-Fi",
    Rating: 4.2
  },
  {
    id: 39,
    Title: "The Last of the Mohicans",
    Author: "James Fenimore Cooper",
    PublicationDate: 1826,
    Pages: 337,
    CoverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD5MSqXaZB6BHkdu1vb0UFeQMo-P0R_6AbsA&s",
    Description: "Set during the French and Indian War, it follows the journey of the last members of the Mohican tribe.",
    Category: "Historical Fiction",
    Rating: 4.5
  },
  {
    id: 40,
    Title: "The Odyssey",
    Author: "Homer",
    PublicationDate: "8th Century BC",
    Pages: 541,
    CoverImage: "https://m.media-amazon.com/images/I/A1JR2oK-orL._AC_UF1000,1000_QL80_.jpg",
    Description: "The epic tale of Odysseus' long and dangerous journey home after the Trojan War.",
    Category: "Classics",
    Rating: 4.7
  }
];
